; This is an .INI file, used as a simple way to tune a game without recompiling/hardcoding it.
; A great place for gameplay variables and more. Another example of data-driven programming. 
[Level1]
levelFile=../Levels/SimulationLevel.json
modelPath=../Levels/Models
[Player]
model=FreeCam
moveSpeed=30.0
camSpeed=1.0

[Sun]
model=Sun
posX = 0
posY = 0
posZ = 0
scale = 3.15
rotSpeed = 10
[Mercury]
model=Mercury
posX = 0
posY = 0
posZ = 15
scale = 0.8
rotSpeed = 40
[Venus]
model=Venus
posX = 0
posY = 0
posZ = 25
scale = 1
rotSpeed = 35
[Earth]
model=Earth
posX = 0
posY = 0
posZ = 35 
scale = 1
rotSpeed = 30
[Mars]
model=Mars
posX = 0
posY = 0
posZ = 50
scale = 0.8
rotSpeed = 25
[Jupiter]
model=Jupiter
posX = 0
posY = 0
posZ = 75
scale = 4.75
rotSpeed = 20
[Saturn]
model=Saturn
posX = 0
posY = 0
posZ = 115
scale = 2.8
rotSpeed = 15
[Uranus]
model=Uranus
posX = 0
posY = 0
posZ = 150
scale = 1.7
rotSpeed = 10
[Neptune]
model=Neptune
posX = 0
posY = 0
posZ = 200
scale = 1.6
rotSpeed = 5
[Moon]
model=Moon
posX = 0
posY = 0
posZ = 0
scale = 0.3
rotSpeed = 360

[Shaders]
pixel=../Shaders/LevelPixel.hlsl
vertex=../Shaders/LevelVertex.hlsl
[Window]
height=768
width=1024
xstart=100
ystart=100
[Render]
near=0.001
far=1000
fov=90
; If you change this file it will replace the saved.ini version if its newer. 